
Metrics/MethodLength:
  Max: 20

Metrics/MethodCount:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ModuleLength:
  Max: 250

Style/RescueModifier:
  Enabled: false